# This file generates the labeling information for the nuscenes dataset in the semantic-kitti format. 
labels: 
  0 : "noise"
  1 : "animal"
  2 : "human.pedestrian.adult"
  3 : "human.pedestrian.child"
  4 : "human.pedestrian.construction_worker"
  5 : "human.pedestrian.personal_mobility"
  6 : "human.pedestrian.police_officer"
  7 : "human.pedestrian.stroller"
  8 : "human.pedestrian.wheelchair"
  9 : "movable_object.barrier"
  10: "movable_object.debris"
  11: "movable_object.pushable_pullable"
  12: "movable_object.trafficcone"
  13: "static_object.bicycle_rack"
  14: "vehicle.bicycle"
  15: "vehicle.bus.bendy"
  16: "vehicle.bus.rigid"
  17: "vehicle.car"
  18: "vehicle.construction"
  19: "vehicle.emergency.ambulance"
  20: "vehicle.emergency.police"
  21: "vehicle.motorcycle"
  22: "vehicle.trailer"
  23: "vehicle.truck"
  24: "flat.driveable_surface"
  25: "flat.other"
  26: "flat.sidewalk"
  27: "flat.terrain"
  28: "static.manmade"
  29: "static.other"
  30: "static.vegetation"
  31: "vehicle.ego"
labels_coarse:
  0 : "noise"
  1 : "barrier"
  2 : "bicycle"
  3 : "bus"
  4 : "car"
  5 : "construction_vehicle"
  6 : "motorcycle"
  7 : "pedestrian"
  8 : "traffic_cone"
  9 : "trailer"
  10: "truck"
  11: "driveable_surface"
  12: "other_flat"
  13: "sidewalk"
  14: "terrain"
  15: "manmade"
  16: "vegetation"
learning_map: # according to python-sdk/nuscenes/eval/lidarseg/utils.py get_fine2coarse()
  0: 0
  1: 0
  2: 7
  3: 7
  4: 7
  5: 0
  6: 7
  7: 0
  8: 0
  9: 1
  10: 0
  11: 0
  12: 8
  13: 0
  14: 2
  15: 3
  16: 3
  17: 4
  18: 5
  19: 0
  20: 0
  21: 6
  22: 9
  23: 10
  24: 11
  25: 12
  26: 13
  27: 14
  28: 15
  29: 0
  30: 16
  31: 0
learning_map_inv:
  0 : 0
  1 : 9
  2 : 14
  3 : 15
  4 : 17
  5 : 18
  6 : 21
  7 : 2
  8 : 12
  9 : 22
  10: 23
  11: 24
  12: 25
  13: 26
  14: 27
  15: 28
  16: 30
learning_ignore:
  0: True
  1: False 
  2: False 
  3: False 
  4: False 
  5: False 
  6: False 
  7: False 
  8: False 
  9: False 
  10: False
  11: False
  12: False
  13: False
  14: False
  15: False
  16: False
split:  # nuscenes sequence numbers for train, valid, test
  train: [0384,0476,0207,0299,0377,0586,0461,0053,0374,0577,0350,0371,0856,0870,0574,0687,0450,0250,0008,0292,0178,0433,0398,0392,0182,0851,0285,0706,0535,0714,0001,0580,0214,0259,0042,0356,0151,0177,0444,0474,0171,0425,0458,0709,0069,0695,0514,0020,0152,0348,0184,0759,0010,0427,0528,0816,0710,0676,0046,0543,0029,0061,0573,0654,0026,0060,0585,0670,0787,0810,0421,0172,0479,0661,0162,0373,0449,0210,0204,0231,0510,0815,0360,0002,0674,0708,0175,0500,0511,0120,0698,0418,0248,0009,0645,0249,0502,0263,0664,0297,0057,0375,0703,0683,0644,0155,0597,0733,0517,0760,0509,0234,0365,0074,0452,0475,0224,0382,0367,0525,0133,0671,0032,0650,0024,0852,0067,0228,0188,0199,0430,0167,0669,0073,0512,0527,0362,0041,0428,0667,0021,0736,0672,0600,0397,0190,0806,0855,0050,0598,0808,0055,0713,0154,0300,0303,0390,0402,0545,0790,0668,0658,0572,0007,0286,0125,0588,0868,0508,0262,0381,0044,0847,0675,0181,0544,0284,0034,0168,0518,0063,0731,0819,0432,0260,0209,0717,0283,0469,0306,0159,0255,0515,0150,0593,0789,0408,0296,0124,0747,0183,0075,0200,0134,0163,0031,0195,0438,0239,0757,0328,0677,0291,0407,0716,0656,0752,0539,0400,0368,0718,0179,0726,0863,0241,0229,0045,0506,0406,0820,0304,0383,0440,0507,0246,0704,0700,0803,0123,0126,0566,0751,0064,0238,0353,0504,0647,0420,0764,0054,0047,0388,0685,0640,0869,0230,0529,0451,0028,0653,0247,0739,0453,0537,0643,0728,0448,0302,0318,0317,0805,0149,0534,0791,0812,0591,0051,0767,0030,0347,0571,0712,0696,0854,0403,0719,0193,0243,0454,0590,0358,0355,0429,0501,0741,0860,0422,0817,0456,0352,0305,0701,0316,0663,0235,0684,0165,0379,0673,0749,0443,0264,0351,0232,0765,0354,0592,0419,0705,0811,0459,0513,0219,0071,0848,0376,0646,0244,0011,0361,0467,0455,0505,0160,0315,0768,0865,0131,0218,0648,0208,0468,0478,0194,0595,0394,0192,0323,0411,0437,0822,0424,0412,0715,0170,0022,0226,0866,0236,0127,0738,0665,0499,0697,0465,0740,0072,0861,0441,0138,0666,0157,0237,0203,0410,0389,0858,0174,0059,0727,0762,0364,0763,0396,0688,0321,0139,0813,0542,0711,0769,0758,0707,0395,0435,0576,0372,0570,0413,0679,0357,0415,0068,0477,0288,0393,0052,0369,0639,0122,0158,0850,0439,0187,0472,0541,0416,0599,0642,0792,0251,0366,0744,0233,0584,0641,0056,0295,0253,0121,0761,0043,0023,0568,0173,0434,0176,0006,0750,0862,0651,0681,0386,0033,0349,0128,0649,0027,0062,0431,0689,0166,0222,0076,0245,0538,0464,0583,0380,0463,0652,0737,0065,0589,0240,0254,0471,0242,0019,0399,0185,0457,0442,0405,0730,0659,0735,0804,0066,0058,0161,0480,0289,0746,0257,0132,0070,0211,0391,0531,0786,0821,0462,0536,0546,0180,0252,0401,0414,0578,0864,0206,0532,0370,0582,0164,0594,0212,0290,0005,0004,0587,0324,0423,0853,0135,0533,0359,0129,0734,0662,0446,0294,0227,0301,0287,0225,0130,0220,0025,0048,0678,0256,0575,0213,0426,0445,0447,0196,0655,0686,0436,0809,0049,0261,0378,0657,0202,0258,0385,0417,0530,0660,0293,0363,0849,0191,0526,0298,0596]
  valid: [0003,0012,0013,0014,0015,0016,0017,0018,0035,0036,0038,0039,0092,0093,0094,0095,0096,0097,0098,0099,0100,0101,0102,0103,0104,0105,0106,0107,0108,0109,0110,0221,0268,0269,0270,0271,0272,0273,0274,0275,0276,0277,0278,0329,0330,0331,0332,0344,0345,0346,0519,0520,0521,0522,0523,0524,0552,0553,0554,0555,0556,0557,0558,0559,0560,0561,0562,0563,0564,0565,0625,0626,0627,0629,0630,0632,0633,0634,0635,0636,0637,0638,0770,0771,0775,0777,0778,0780,0781,0782,0783,0784,0794,0795,0796,0797,0798,0799,0800,0802,0904,0905,0906,0907,0908,0909,0910,0911,0912,0913,0914,0915,0916,0917,0919,0920,0921,0922,0923,0924,0925,0926,0927,0928,0929,0930,0931,0962,0963,0966,0967,0968,0969,0971,0972,1059,1060,1061,1062,1063,1064,1065,1066,1067,1068,1069,1070,1071,1072,1073]
color_map: #bgr
  0 : [0, 0, 0]
  2 : [230, 0, 0]
  3 : [230, 0, 0]
  8 : [0, 0, 0]
  7 : [0, 0, 0]
  5 : [0, 0, 0]
  6 : [230, 0, 0]
  4 : [230, 0, 0]
  1 : [0, 0, 0]
  17: [0, 158, 255]
  21: [99, 61, 255]
  14: [60, 20, 220]
  15: [80, 127, 255]
  16: [80, 127, 255]
  23: [71, 99, 255]
  18: [70, 150, 233]
  19: [0, 0, 0]
  20: [0, 0, 0]
  22: [0, 140, 255]
  9 : [144, 128, 112]
  12: [79, 79, 47]
  11: [0, 0, 0]
  10: [0, 0, 0]
  13: [0, 0, 0]
  24: [191, 207, 0]
  26: [75, 0, 75]
  27: [60, 180, 112]
  25: [75, 0, 175]
  28: [135, 184, 222]
  30: [0, 175, 0]
  29: [0, 0, 0]
  31: [0, 0, 0]
content:
  0: 0.004271014955953988
  1: 0.0
  2: 0.0025220872131016554
  3: 0.0
  4: 0.00012172579894928788
  5: 0.00030534002608231624
  6: 4.993878931252836e-06
  7: 0.0
  8: 0.0
  9: 0.004549067000733387
  10: 4.191291245872916e-06
  11: 5.21681995496948e-05
  12: 0.0004662142687962469
  13: 0.0
  14: 6.71498363434533e-05
  15: 0.003485014082738586
  16: 0.0018324860385413309
  17: 0.033095416617916894
  18: 0.002690808979850412
  19: 0.0
  20: 0.0
  21: 0.00025129912193340166
  22: 0.001125495464131108
  23: 0.024810214765330494
  24: 0.28204170816342256
  25: 0.013387786827003473
  26: 0.05443773917113024
  27: 0.05103289468052016
  28: 0.141929962988223
  29: 0.001487640863056425
  30: 0.11677169269666608
  31: 0.25925588706984865